"""
Integration Hub for JsonAI.

This module provides integrations with popular developer tools and platforms,
making JsonAI easily embeddable into existing workflows.
"""

import asyncio
import json
import os
from typing import Dict, Any, List, Optional, Callable
from datetime import datetime
import requests
from pathlib import Path

from jsonAI.main import Jsonformer
from jsonAI.model_backends import ModelBackend


class GitHubIntegration:
    """GitHub integration for JsonAI."""

    def __init__(self, token: Optional[str] = None):
        self.token = token or os.getenv("GITHUB_TOKEN")
        self.base_url = "https://api.github.com"
        self.headers = {"Authorization": f"token {self.token}"} if self.token else {}

    def create_issue_with_generated_data(self, repo: str, title: str,
                                       jsonformer: Jsonformer, prompt: str) -> Dict[str, Any]:
        """Create a GitHub issue with generated JSON data."""

        # Generate data
        generated_data = jsonformer.generate_data(prompt)

        # Format issue body
        body = f"""## Generated Data

```json
{json.dumps(generated_data, indent=2)}
```

*Generated by JsonAI on {datetime.now().isoformat()}*"""

        # Create issue
        url = f"{self.base_url}/repos/{repo}/issues"
        data = {
            "title": title,
            "body": body,
            "labels": ["jsonai-generated", "automated"]
        }

        response = requests.post(url, json=data, headers=self.headers)
        response.raise_for_status()

        return response.json()

    def generate_from_issue(self, repo: str, issue_number: int,
                           jsonformer: Jsonformer) -> Dict[str, Any]:
        """Generate data based on GitHub issue content."""

        # Get issue
        url = f"{self.base_url}/repos/{repo}/issues/{issue_number}"
        response = requests.get(url, headers=self.headers)
        response.raise_for_status()

        issue_data = response.json()
        issue_body = issue_data.get("body", "")
        issue_title = issue_data.get("title", "")

        # Use issue content as prompt
        prompt = f"Based on this GitHub issue: {issue_title}\n\n{issue_body}"

        # Generate data
        generated_data = jsonformer.generate_data(prompt)

        return {
            "issue": issue_data,
            "generated_data": generated_data
        }


class SlackIntegration:
    """Slack integration for JsonAI."""

    def __init__(self, token: Optional[str] = None):
        self.token = token or os.getenv("SLACK_TOKEN")
        self.base_url = "https://slack.com/api"
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json"
        }

    def post_generated_data(self, channel: str, jsonformer: Jsonformer,
                           prompt: str, title: str = "Generated Data") -> Dict[str, Any]:
        """Post generated JSON data to Slack channel."""

        # Generate data
        generated_data = jsonformer.generate_data(prompt)

        # Format message
        message = {
            "channel": channel,
            "text": title,
            "blocks": [
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*{title}*\n\n```json\n{json.dumps(generated_data, indent=2)}\n```"
                    }
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": f"Generated by JsonAI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
                        }
                    ]
                }
            ]
        }

        # Post to Slack
        url = f"{self.base_url}/chat.postMessage"
        response = requests.post(url, json=message, headers=self.headers)
        response.raise_for_status()

        return response.json()

    async def handle_slack_command(self, command_text: str,
                                  jsonformer: Jsonformer) -> str:
        """Handle Slack slash commands for JsonAI."""

        # Parse command
        parts = command_text.strip().split()
        if len(parts) < 2:
            return "Usage: /jsonai generate <prompt>"

        action = parts[0].lower()
        prompt = " ".join(parts[1:])

        if action == "generate":
            # Generate data
            generated_data = jsonformer.generate_data(prompt)

            # Format response
            response = f"Here's your generated data:\n```json\n{json.dumps(generated_data, indent=2)}\n```"
            return response

        return f"Unknown action: {action}"


class VSCodeIntegration:
    """VS Code extension integration for JsonAI."""

    def __init__(self):
        self.extension_id = "jsonai.jsonai-vscode"

    def generate_schema_from_file(self, file_path: str,
                                 jsonformer: Jsonformer) -> Dict[str, Any]:
        """Generate JSON schema from a file's content."""

        with open(file_path, 'r') as f:
            content = f.read()

        # Analyze file content to determine schema
        file_ext = Path(file_path).suffix.lower()

        if file_ext == '.json':
            # Try to infer schema from JSON structure
            try:
                data = json.loads(content)
                schema = self._infer_schema_from_data(data)
            except:
                schema = {"type": "object", "properties": {}}
        else:
            # Generate generic schema
            schema = {
                "type": "object",
                "properties": {
                    "content": {"type": "string"},
                    "metadata": {"type": "object"}
                }
            }

        # Update jsonformer with new schema
        jsonformer.json_schema = schema

        return schema

    def _infer_schema_from_data(self, data: Any) -> Dict[str, Any]:
        """Infer JSON schema from data structure."""
        if isinstance(data, dict):
            properties = {}
            for key, value in data.items():
                properties[key] = self._infer_schema_from_data(value)
            return {"type": "object", "properties": properties}
        elif isinstance(data, list):
            if data:
                return {"type": "array", "items": self._infer_schema_from_data(data[0])}
            else:
                return {"type": "array", "items": {"type": "string"}}
        elif isinstance(data, str):
            return {"type": "string"}
        elif isinstance(data, int):
            return {"type": "integer"}
        elif isinstance(data, float):
            return {"type": "number"}
        elif isinstance(data, bool):
            return {"type": "boolean"}
        else:
            return {"type": "string"}

    def create_vscode_snippet(self, schema: Dict[str, Any], name: str) -> Dict[str, Any]:
        """Create a VS Code snippet from JSON schema."""

        # Generate sample JSON from schema
        sample_data = self._generate_sample_from_schema(schema)

        snippet = {
            "prefix": f"jsonai-{name}",
            "body": json.dumps(sample_data, indent=4),
            "description": f"JsonAI generated snippet for {name}"
        }

        return snippet

    def _generate_sample_from_schema(self, schema: Dict[str, Any]) -> Any:
        """Generate sample data from JSON schema."""
        schema_type = schema.get("type", "object")

        if schema_type == "object":
            result = {}
            properties = schema.get("properties", {})
            for key, prop_schema in properties.items():
                result[key] = self._generate_sample_from_schema(prop_schema)
            return result
        elif schema_type == "array":
            items_schema = schema.get("items", {"type": "string"})
            return [self._generate_sample_from_schema(items_schema)]
        elif schema_type == "string":
            return "sample_string"
        elif schema_type == "integer":
            return 42
        elif schema_type == "number":
            return 3.14
        elif schema_type == "boolean":
            return True
        else:
            return "sample"


class WebhookIntegration:
    """Webhook integration for real-time JsonAI notifications."""

    def __init__(self):
        self.webhooks: Dict[str, List[str]] = {}
        self.event_handlers: Dict[str, List[Callable]] = {}

    def register_webhook(self, event: str, url: str):
        """Register a webhook URL for an event."""
        if event not in self.webhooks:
            self.webhooks[event] = []
        self.webhooks[event].append(url)

    def register_event_handler(self, event: str, handler: Callable):
        """Register an event handler function."""
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    async def trigger_event(self, event: str, data: Dict[str, Any]):
        """Trigger an event and notify all registered webhooks and handlers."""

        # Call event handlers
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    if asyncio.iscoroutinefunction(handler):
                        await handler(event, data)
                    else:
                        handler(event, data)
                except Exception as e:
                    print(f"Event handler error: {e}")

        # Send webhooks
        if event in self.webhooks:
            for url in self.webhooks[event]:
                try:
                    payload = {
                        "event": event,
                        "data": data,
                        "timestamp": datetime.now().isoformat()
                    }
                    response = requests.post(url, json=payload, timeout=5)
                    response.raise_for_status()
                except Exception as e:
                    print(f"Webhook error for {url}: {e}")

    async def on_generation_complete(self, generation_data: Dict[str, Any]):
        """Handle generation complete events."""
        await self.trigger_event("generation_complete", generation_data)

    async def on_agent_response(self, agent_data: Dict[str, Any]):
        """Handle agent response events."""
        await self.trigger_event("agent_response", agent_data)

    async def on_error(self, error_data: Dict[str, Any]):
        """Handle error events."""
        await self.trigger_event("error", error_data)


class IntegrationHub:
    """Central hub for managing all JsonAI integrations."""

    def __init__(self):
        self.github = GitHubIntegration()
        self.slack = SlackIntegration()
        self.vscode = VSCodeIntegration()
        self.webhooks = WebhookIntegration()
        self.integrations: Dict[str, Any] = {
            "github": self.github,
            "slack": self.slack,
            "vscode": self.vscode,
            "webhooks": self.webhooks
        }

    def get_integration(self, name: str) -> Optional[Any]:
        """Get an integration by name."""
        return self.integrations.get(name)

    def enable_integration(self, name: str, config: Dict[str, Any]):
        """Enable and configure an integration."""
        integration = self.get_integration(name)
        if integration and hasattr(integration, 'configure'):
            integration.configure(config)

    def list_available_integrations(self) -> List[str]:
        """List all available integrations."""
        return list(self.integrations.keys())
