name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"] # Focus on supported versions

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Build package
      run: poetry build

    - name: Lint with flake8
      run: |
        poetry run flake8 .
    - name: Test with pytest and Coverage
      run: |
        poetry run pytest --cov=jsonAI --cov-report=xml # Run tests with coverage and generate XML report
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Ensure you have a CODECOV_TOKEN secret in your repo settings
        files: ./coverage.xml # Path to the coverage report file
        fail_ci_if_error: true # Fail CI if Codecov upload fails
